### ISSUE TITLE
New IInput Decorator "SelfClosing"

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#113]
### Bug Report or Feature Request (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Expected Behavior
We have a new Decorator for IInput called  'SelfDisposing'. Its purpose is to replace using statement. It closes a stream after it is done with reading.

**Comment by ICACLE** [comment]
@Meerownymous My idea was to react on an event like 'read to end'. But the stream class didn't have such a event, so i will do a own overriden Stream class which have!? Are events unelegant? I dont want to dispose in Stream class itself because i need to call the dispose methode of the origin IInput to get a real decorator.

**Comment by DFU398** [comment]
I don't see how a decorator pattern would mimic the behavior of a using statement, because the using statement has a clear end at which the stream is disposed, whereas an IInput decorator would return a stream and anything could be done to that stream. The Stream class does not expose events, so how would the decorator know when to dispose the stream?

I think it might make sense to create a new implementation of IAction that replaces the using statement:
```csharp
public sealed class SelfDisposing : IAction
{
    private readonly IInput input;
    private readonly IAction<Stream> action;

    public SelfDisposing(IInput input, IAction<Stream> action)
    {
        this.input = input;
        this.action= action;
    }
    public void Invoke()
    {
        this.action.Invoke(input.Stream());
        this.input.Stream.Close();
        this.input.Stream.Dispose();
    }
}
```
that way a using statement like this
```csharp
using(var stream = File.OpenRead( /* filename */ ))
{
    /* do something */
} // stream gets disposed here
```
could be replaced with this:
```csharp
new SelfDisposing(
    new InputOf(new Uri( /* filename */ )),
    (stream) =>
    {
        /* do somethig */
    } // stream gets disposed here
).Invoke()
```
Any feedback on this idea?
I'm not sure if this would be necessary, because the using statement seems easier to use.

**Comment by Meerownymous** [comment]
I agree, I do not see a way for self disposing either, your reasoning is correct. It hasnt gone enough thought into it when writing this issue.

Making all IInputs disposable is not suitable too, for reasons stated.

We should stick with the current design paradigm: Decorators leave the stream open. Classes which return something else, like lengthof, should by default close the stream. If we find usecases where we need these classes to remain the stream open, we can make it configurable by injecting a flag into their ctor.
