### ISSUE TITLE
Analyze the usage of GitLink for our projects

### ISSUE THREAD

**Issue by Meerownymous** [icarus-consulting/Yaapii.Atoms#120]
[Gitlink](https://github.com/GitTools/GitLink) seems to be useful: It says it allows us to step through code which is on github. Can we use it?

Please analyse it: Try to use GitLink to step through our Atoms code while coding in another Repo.

**Comment by aveXcaesar** [comment]
Result:
Useful information's:
- Open questions after reading readme.md answerd here: https://github.com/GitTools/GitLink/issues/148
- Test Repository: https://github.com/StephenCleary/GitLinkTestLib

What I have done:
- New Branch: https://github.com/icarus-consulting/Yaapii.Atoms/tree/i120-GitLink
- To make Gitlink working we need a pdb file which contains the path's to the source file's on github. For creation of this we have only to reference the GitLink nuget repository in the Atoms project (done). Then on the build process the pdb fiiles will get the needed path's.
- When I build with VS no error occures. Checking the pdb file I can find local path's to the atom's soruce files (...\Yaapii.Atoms\src\Yaapii.Atoms\bin\Release\netstandard2.0\netstandard2.0\Yaapii.Atoms.pdb). **This looks good**.
- When I try to build with the cake script the following error occures (same on the AppVayor):
```
========================================
Build
========================================
Microsoft (R)-Buildmodul, Version 15.5.180.51428 für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Restore completed in 15,31 ms for C:\Users\csa\Source\Git\Yaapii.Atoms\src\Yaapii.Atoms\Yaapii.Atoms.csproj.
C:\Users\csa\.nuget\packages\gitlink\3.1.0\build\GitLink.targets(9,5): error MSB4062: Die LinkPdbToGitRemote-Aufgabe konnte nicht aus der C:\Users\csa\.nuget\packages\gitlink\3.1.0\build\GitLinkTask.dll-Assembly geladen werden. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden. Stellen Sie sicher, dass die <UsingTask>-Deklaration korrekt ist, die Assembly und alle zugehörigen Abhängigkeiten verfügbar sind und die Aufgabe eine öffentliche Klasse enthält, die Microsoft.Build.Framework.ITask implementiert. [C:\Users\csa\Source\Git\Yaapii.Atoms\src\Yaapii.Atoms\Yaapii.Atoms.csproj]

Fehler beim Buildvorgang.

C:\Users\csa\.nuget\packages\gitlink\3.1.0\build\GitLink.targets(9,5): error MSB4062: Die LinkPdbToGitRemote-Aufgabe konnte nicht aus der C:\Users\csa\.nuget\packages\gitlink\3.1.0\build\GitLinkTask.dll-Assembly geladen werden. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden. Stellen Sie sicher, dass die <UsingTask>-Deklaration korrekt ist, die Assembly und alle zugehörigen Abhängigkeiten verfügbar sind und die Aufgabe eine öffentliche Klasse enthält, die Microsoft.Build.Framework.ITask implementiert. [C:\Users\csa\Source\Git\Yaapii.Atoms\src\Yaapii.Atoms\Yaapii.Atoms.csproj]
    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:00.61
An error occurred when executing task 'Build'.
Error: Mindestens ein Fehler ist aufgetreten.
        .NET Core CLI: Process returned an error (exit code 1).
```
The goal is to have the file path's to the atoms nuget package in the pdb file and reach this goal on the AppVeyor. When the pdb files are published with the nuget package VS is able to find the online sources.
But the cake script fails because unknown reason (local and on the AppVeyor).
- I created a new clean solution (Net461) and referenced the StephanCleary.GitLintTestLib nuget package. I enabled "Enable source server support" in the VS options. My expectation is to be able to step in the delivered methods of the testLib but it doesn't work. What's wrong?!

Stop working here because of time limitation.

**Comment by Meerownymous** [comment]
Closed due to inactivity.
