### ISSUE TITLE
ItemAt don't throw given exception

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Atoms#272]
### Expected Behavior

The given exception is thrown
### Actual Behavior

only standard exception is thrown
### Mention any other details that might be useful

error is in ItemAtEnumerator: 
```
 new FailPrecise(
                new FailWhen(this._pos < 0),
                new UnsupportedOperationException(
                    new FormattedText("The position must be non-negative but is {0}",
this._pos).AsString())).Go();
```

**Comment by DFU398** [comment]
By "given exception", do you mean a given fallback function which throws an exception? Because there is no way to directly give an exception to ItemAt, as none of its constructors or methods take an exception as an argument. 
Does this mean you want the fallback function to be called when the given position is negative?
In that case this does not look like an error, because the code does what it is supposed to do, although it isn't what you want it to do, which would make this a feature request.
Please clarify if i interpreted this correctly, because you're not exactly giving a wealth of information about the issue.

**Comment by icaOBU** [comment]
@DFU398  ItemAt has ctors like [this](https://github.com/icarus-consulting/Yaapii.Atoms/blob/6e8da080e08b5f64466088c3b9d9e6954627a08a/src/Yaapii.Atoms/Scalar/ItemAt.cs#L49)  one, where I can inject a specific Exception. This injected exception never thrown, if an error occurs, only the standard exception of ItemAtEnumerator. 
ItemAt uses internally the ItemAtEnumerator (Maybe now Enumerator.ItemAt?) class, for which your dicribed behaviour is correct.
