### ISSUE TITLE
Add SortedMap

### ISSUE THREAD

**Issue by pz1337** [icarus-consulting/Yaapii.Atoms#346]
### Expected Behavior

There's a class that supports sorting (e.g. a list of) KeyValuePairs by value or an attribute of the value.
### Actual Behavior

There's no such class.
### Mention any other details that might be useful

KVPs don't implement the IComparable interface.
There's an IComparer interface.

**Comment by Meerownymous** [comment]
Changed the issue. 

What we need, is a Map decorator which sorts by a given comparer.

We should also make a comparer, which implements IComparer, that knows how to compare a KeyValuePair whose Key is a string.

Since we always have three Map implementations, one string to string, one string to Type and one type to type, we also must do that with the new Map.Sorted class. 

We can use that comparer by default when implementing:

Map.Sorted<string,string> and for Map.Sorted<string,T>.

**Comment by Meerownymous** [comment]
@robcadhacker still working on this? If not, please unassign :)

**Comment by robcadhacker** [comment]
A branch with Map.Sorted() exists but the tests are still missing

**Comment by Meerownymous** [comment]
Should be solved using https://docs.microsoft.com/de-de/dotnet/api/system.collections.generic.sorteddictionary-2?view=netframework-4.8

**Comment by pz1337** [comment]
> Should be solved using https://docs.microsoft.com/de-de/dotnet/api/system.collections.generic.sorteddictionary-2?view=netframework-4.8

> Represents a collection of key/value pairs that are sorted on the key.

According to the description this issue will not be solved because we want to sort "KeyValuePairs by value or an attribute of the value."
