### ISSUE TITLE
Add Sliced IEnumerable

### ISSUE THREAD

**Issue by jaanpeeter** [icarus-consulting/Yaapii.Atoms#469]
### Expected Behavior
We have an implementation of IEnumerable which can filter a slice out of the enumerable by a condition for the start item and a condition of the end item. Items in between do not have to fulfil a condition.

### Actual Behavior
We have not

### Mention any other details that might be useful
````
 public sealed class Sliced<T> : ListEnvelope<T>
    {
        /// <summary>
        /// Return a slice of a IEnumerable.
        /// Contains the itmes betwenn the firstItem fulfilling the start condition and the first Item fulfilling the endCondition.
        /// Contains also the Items fulfilling the conditions
        /// </summary>
        public Sliced(IEnumerable<T> origin, Func<T, bool> startCondition, Func<T, bool> endCondition) : base(() =>
        {
            var filtered = new List<T>();

            bool add = false;
            foreach (var item in origin)
            {
                if (startCondition.Invoke(item))
                {
                    add = true;
                }
                if (add)
                {
                    filtered.Add(item);
                    if (endCondition.Invoke(item))
                    {
                        add = false;
                        break;
                    }
                }
            }
            return filtered;
        },false)
        { }
    }
```
'

### Steps to reproduce the behavior


### The log given by the failure.

**Comment by Meerownymous** [comment]
This can already be solved by combining ItemAt and HeadOf + TailOf (of the Many namespace).

Please note that for Atoms to stay performant, it is not a good practice to use List and List.Add for a full List building in the ctor.
Instead, make an inner Enumerator or use the "Many" implementations because otherwise the whole list will be built even if we do only need the first item of it. Implementiung an own enumerator instead will only compile the items that the enumerator is moved to and not more.
