### ISSUE TITLE
Undo Breaking Change for Each<T>

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Atoms#513]
### Expected Behavior
No breaking change

### The log given by the failure.

**Comment by Meerownymous** [comment]
@icaOBU @koeeenig I am against this, I rejected another issue regarding this before - most of the other libraries are already upgraded. It would be better to upgrade the remaining than introducing obsolete attributes into Atoms.

**Comment by koeeenig** [comment]
@Meerownymous Class has been re-added to not break third party software which is not in our control since 2.6.0 introduced a breaking change which was not reflected in the version which violates our semantic versioning rule. I have added an issue #515 which is part of the next major [milestone](https://github.com/icarus-consulting/Yaapii.Atoms/milestone/56)

**Comment by Meerownymous** [comment]
I considered it a bugfix, since the object was placed in the wrong namespace. 3rd party software could update the namespace when upgrading Atoms version.
