### ISSUE TITLE
Sorted is always lazy

### ISSUE THREAD

**Issue by aveXcaesar** [icarus-consulting/Yaapii.Atoms#530]
### Expected Behavior
I can use `Map.Sorted` as intuitive expected.

### Actual Behavior
Using Sorted like this: 
```csharp
var sorted =
    new Sorted<TypeA, TypeB>(
        myDictionary,
        new MyComparer()
    );

sorted.Values;    // throws Exception
```

Throws the following exception: 
```
System.InvalidOperationException: Cannot get the enumerator because this is a lazy dictionary. Enumerating the entries would build all values. If you need this behaviour, set the ctor param 'rejectBuildingAllValues' to false.
```

There is no way to manipulate the intern used `LazyDict` and lazy `KvpPf` for non lazy usage.

### Mention any other details that might be useful
Suggestion:
Introduce a `SortedNonLazy` and a `Sorted` to prevent a breaking change
or (better from my perspective)
Refactor `Sorted` as not lazy and introduce `LazySorted` analoge to `LazyMap`

### The log given by the failure.

**Comment by MSE1188** [comment]
The Yaapii.Atoms.Map classes are build around lazy calling and though do not allow calling ```map.Values```, because behind values can be code executions (e.g. http-calls, etc..). 
Also MapOf does not work with this (```new MapOf(new KvpOf("1", "a")).Values``` throws the same exception)

The simple workaround to retrieve the values is this, which exposes the code excecution of every entry in the map:
```csharp
var values = 
   new Mapped<string, string>(
      key => map[key],
      map.Keys
   );
```
