### ISSUE TITLE
Big nesting of enumerables lead to application crashes.

### ISSUE THREAD

**Issue by MSE1188** [icarus-consulting/Yaapii.Atoms#540]
### Expected Behavior
Enumerable classes work with big nested object calls.

### Actual Behavior
When nesting enumerables atoms classes inside each other over a thousand or 2000 times, the application crashes completely without any stacktrace whatsoever, making it hard to analyze the reason behind this. The behaviour is reproducable with mentioned Unit-Tests below.

### Steps to reproduce the behavior
Build a nested object with 2000 enumerable calls nested inside each other.
Evaluate its length -> App crashes completely without any message.

UnitTest Joined class:
```csharp
        [Fact]
        public void WorksWithBigNestings()
        {
            IEnumerable<string> list = new ManyOf<string>();

            for (int i = 0; i < 2000; i++)
            {
                list = new Joined<string>(list, (i*Math.PI).ToString());
            }

            Assert.Equal(
                2000,
                new LengthOf(list).Value()
            );
        }
```

UnitTest Mapped class:
```csharp
        [Fact]
        public void WorksWithBigNestings()
        {
            IEnumerable<string> list = new ManyOf<string>("0", "1", "2", "3", "4", "5", "6", "7", "8", "9");

            for (int i = 0; i < 2000; i++)
            {
                list =
                    new Mapped<double, string>(
                        v => new TextOf(v).AsString(),
                        new Mapped<string, double>(
                            v => new DoubleOf(v).Value(),
                            list
                        )
                    );
            }

            Assert.Equal(
                new ManyOf<string>("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"),
                list
            );
        }
```
### The log given by the failure.

**Comment by Meerownymous** [comment]
I could reproduce and found the cause to be a StackOverflowException. The stack is indeed polluted with a tremendous amount of nested calls, which makes me think the caching mechanism of enumerables and map/kvp need revision.

In the original cactoos, where all objects were live, Joining worked by putting multiple enumerators into one object, which simply walked over them until the end of each.
The current atoms approach causes a lot of copying and analyzing, for example using LengthOf to initialize arrays, and copying instead of using the original enumerable/enummerator. This seems to be inefficient while inflating the call stack.

**Comment by Meerownymous** [comment]
Update: The caching mechanism - although it might still be too expensive - seems to not be the problem.

The problem seems to occur due to recursion of lambda functions in the constructors.
For example, ManyEnvelope and other objects take a func in the primary ctor and place it in a member. When decorating this object with similar objects multiple times, each call to GetEnumerator results in the lambda in the objects ctor to be executed, then causing the next deeper objects lambda to start executing and so on. The functions do not complete, the stack fills up and therefore a StackOverFlowException is raised in the end. I think it is a design problem in the library that we were unaware of when building it. I am surprised that a few thousand calls cause the stack to overflow.

Maybe there is a design princible change that can be applied to avoid this.

I changed some objects to accept only objects instead of func in the main ctor, and it completed without any problem. However, this change would affect the whole library and seems not doable due to dependent software. Maybe there is another solution.

**Comment by MSE1188** [comment]
Thanks for the research, I will test that too. If I find something, I will let you know

**Comment by MSE1188** [comment]
One possible solution, to apparently get rid of this (and which you will hate) is... ... using System.Linq here...

Using the enumerators of ```System.Linq``` instead of our own seems to solve this problem here. Even the ```live``` behaviour seems to work with it:
![image](https://github.com/icarus-consulting/Yaapii.Atoms/assets/31698290/98fd7f1f-9f31-4875-a854-462efffa27be)

However, this would mean that Yaapii.Atoms.Enumerable classes can be seen as an encapsulation of the System.Linq static methods..
```Mapped -> .Select```
```Filtered-> .Where```
```Joined-> .Join```
and so on...

As creator of this library, what do you think about this @Meerownymous ? Are there serious concerns doing this?

**Comment by Meerownymous** [comment]
Well I just ported it, did not create it

I personally would investigate, what LinQ does different - the codebase should be open source. Then I would try to find an object oriented way to do it - since the current problem lies in the decorator pattern, not the object oriented approach itself. 

I still believe that LinQ with its forward-transform-approach does not really fit into the coding style, thus library.

I think it should be at least tested if LinQ invokes the given function for every item before returning the enumerator, because that would be a disadvantage to the object oriented approach..

**Comment by MSE1188** [comment]
I found some code for LinQ [here](https://github.com/microsoft/referencesource/blob/master/System.Core/System/Linq/Enumerable.cs), although I am not sure if its the latest version.

I made a test to check how often the funcs are evaluated and it seems that it works as lazy as our enumerators (test is green, when using the base ctor stated above):
```csharp
[Fact]
public void CheckEvaluationOfEnumerators()
{
    IEnumerable<string> list = new ManyOf<string>("0", "1", "2", "3", "4", "5", "6", "7", "8", "9");
    var count = 0;
    var result =
        new Mapped<string, double>(v =>
            {
                count++;
                return new DoubleOf(v).Value();
            },
            list
        );
    var test = new ItemAt<double>(result, 1).Value();
    Assert.Equal(
        2,
        count
    );
}
```
The code they use is a little mixed up, sometimes they use classes to implement the enumerators, sometimes they use the ```yield return``` statement in a method to prevent early function execution, but it works out.

I also found some handling for multithreading, so I feel tempted, that we just use their Enumerators to take advantage of the experience it contains...

**Comment by Meerownymous** [comment]
I get why its tempting.. 
Does the LinQ approach prevent the stackoverflow while using the decorator pattern? Could you test it? The amount of iterations necessary to trigger it would we mich higher due to inefficiency stated above, but I think there is an upper boundary with LinQ too

**Comment by Meerownymous** [comment]
I did a test with your suggested fix using LinQ, and it proved that there is the same problem. The stackoverflow occurs at a 10x higher iteration count (so, inefficiency proven also) - but it occurs. So it lies in the decorator pattern itself. The LinQ approach would only give more room but not fix it. My conclusion would be to:
1. reduce inefficiency in caching
2. find a way around the decorator pattern in these type of objects

**Comment by MSE1188** [comment]
True, you can even reproduce the behaviour by calling linq-methods often after each other (for instance ```.Select(...).Select(...)...``` 50k times).
I will have a look into this, how to improve the efficiency. The problem occurred in the map.Joined class where for all entries the Joined enumerator was called, which lead to problems on bigger Dictionaries, but we already have a PR to solve this

**Comment by MSE1188** [comment]
Thats very interesting..
I started a draft PR (#545 ) to open code discussion there.
What is really interesting is, that the evaluation of the enumerator in ctor seems to improve the efficiency also in other ways (see discussion there)

**Comment by Meerownymous** [comment]
I would like to continue the discussion in #562
